[package]
name = "lab3"
version = "0.1.0"
authors = ["AmDer <dmitriiartemev@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.9.1"
gio = "0.9.1"
glib = "0.10.3"
cairo-rs = "0.9.1"
gdk = "0.13.2"